### PR TITLE
update encryption section

### PR DESCRIPTION
**Pull request by IC-encipher**
added notes about the order to apply the layers of encryption to the message

### CODE REVIEW

**Comment by xvk-64** [comment]
I think the line about the signatures could be revised. Please look at RSA-PSS, the signature scheme we are using. It is not as simple as you described. Luckily there is support in most crypto libraries for this scheme so we will not have to do it manually as you have described.

**Comment by IC-encipher** [comment]
would saying "create a signature by applying the signature scheme RSA-PSS" work better my main goal with this addition was to explain the order of the encryption and what parts it was applied too

**Comment by IC-encipher** [comment]
note made changes to writing, so it doesn't go into how the signature scheme works

**Comment by xvk-64** [comment]
Looks OK

**Pull request merged**
