### PR TITLE
Protocol defined messages edit

### PR DESCRIPTION
**Pull request by IC-encipher**
Added more notes explaining in greater detail what different parts of the message structure mean in Protocol defined message

### CODE REVIEW

**Comment by xvk-64** [comment]
I would suggest removing the part about base64, its a googleable term. Also the purpose of it is not to reduce the size, its to make binary data into a printable form. It actually increases the size (increase of 25%)

**Comment by IC-encipher** [comment]
that makes sense, will remove however I do think someday we should saying that we are using base54 standard like A-Za-z0-9+/=  which I'm assume is the intention because there are variation on it, thoughts on a better place to put it?

**Comment by xvk-64** [comment]
base64 standard is RFC 4648

**Comment by IC-encipher** [comment]
that is from the internet standards right? Is that mentioned anywhere I have only seen  Websockets (RFC 6455) in the spec. I assume that is included because the reference (RFC 4648) number is less?

**Comment by xvk-64** [comment]
You can add RFC 4648 if you think there is ambiguity in the document

**Comment by IC-encipher** [comment]
removed base64 section and added RFC 3648

**Pull request merged**
